sudo: false
cache: pip
language: python
python:
  - "3.8"
matrix:
  include:
    # lint stage
    - stage: lint
      name: "Check MANIFEST.in"
      env: TOXENV=manifest
    - name: "Check code quality with Flake8"
      env: TOXENV=flake8
    - name: "Check package metadata with Pyroma"
      env: TOXENV=pyroma
    - name: "Check static typing with MyPy"
      env: TOXENV=mypy
    # docs stage
    - stage: docs
      name: "Check RST conformity with doc8"
      env: TOXENV=doc8
    - name: "Check README.rst"
      env: TOXENV=readme
    - name: "Check documentation build with Sphinx"
      env: TOXENV=docs
    # test stage
    - stage: test
      env: TOXENV=py
  allow_failures:
    - env: TOXENV=mypy
    - env: TOXENV=flake8
install:
  - pip install --upgrade pip
  - pip install tox
  - pip install codecov
  - pip install coverage
script:
  - tox
after_success:
  - tox -e coverage-report
  - codecov
notifications:
  slack: pybel:n2KbWKBum3musnBg3L76gGwq
